meteosite/meteosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('previsions/', include('previsions.urls')),
    path('admin/', admin.site.urls),
]

meteosite/previsions/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'previsions'

urlpatterns = [
    path('', views.index, name="index"),
    path('departements/', views.departements, name='departements'),
    path('select_departement/', views.select_departement, name='select_departement'),
    path('display_villes/', views.display_villes, name='display_villes'),
    path('add_ville/', views.add_ville, name='add_ville'),
    path('login/', LoginView.as_view(next_page='/previsions/'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/previsions/login'), name='logout'),
    path('favoris/', views.favoris, name='favoris'),
    path('display_previsions_ville/', views.display_previsions_ville, name='display_previsions_ville'),
]

meteosite/previsions/models.py
from django.db import models


class Departement(models.Model):
    id_departement = models.SmallAutoField(primary_key=True)
    nom = models.CharField(max_length=50, blank=True, null=True)
    code = models.CharField(max_length=3)

    class Meta:
        managed = True
        db_table = 'departement'


class Prevision(models.Model):
    id_prevision = models.AutoField(primary_key=True)
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    temperature_min = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    temperature_max = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    temperature_matin = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    temperature_apres_midi = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    temperature_nuit = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    pression_atmospherique = models.SmallIntegerField(blank=True, null=True)
    humidite = models.SmallIntegerField(blank=True, null=True)
    description = models.CharField(max_length=30)
    direction_vent = models.SmallIntegerField(blank=True, null=True)
    force_vent = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    jour = models.DateField()
    last_update = models.DateField()
    id_ville = models.ForeignKey('Ville', models.DO_NOTHING, db_column='id_ville')

    class Meta:
        managed = True
        db_table = 'prevision'


class Ville(models.Model):
    id_ville = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=60, blank=True, null=True)
    id_departement = models.ForeignKey(Departement, models.DO_NOTHING, db_column='id_departement')
    code_postal = models.IntegerField()
    
    def __str__(self):
        return self.nom

    class Meta:
        managed = True
        db_table = 'ville'

meteosite/previsions/forms.py
from django import forms
from django.forms import ModelChoiceField
from .models import Departement



class DepartementModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.nom

class VilleForm(forms.Form):
    nom = forms.CharField(label='Nom', max_length=40, required=True)
    code_postal = forms.IntegerField(widget=forms.TextInput, label='Code_postal', required=True)
    departement = DepartementModelChoiceField(label='Departement', required=True,
                                              queryset=Departement.objects.all(),
                                              empty_label="Choisir un département")

meteosite/previsions/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .models import Ville, Departement
from .forms import VilleForm
import logging
from .business.components.meteo_ville_previsions import MeteoVillePrevisions
from .utils.helper.ui_helper import UIHelper




logger = logging.getLogger("previsions")

@login_required(login_url=f'/previsions/login/?next=/previsions/login/')
def index(request):

    logger.debug("entrée dans la view index")

    template = loader.get_template('previsions/index.html')
    context = {}

    logger.warning("context vide")

    logger.info("definition des villes favorites pour l'utilisateur")

    liste_villes_favorites = ['lyon', 'paris', 'nantes']
    request.session['favoris'] = liste_villes_favorites
    return HttpResponse(template.render(context, request))

def departements(request):

    # on obtient ici toutes les villes dont la clée étrangère est égale à 1
    #
    # ce qui correspond à la requête SQL :
    # select * from ville where id_departement = 1
    villes_du_departement = Ville.objects.filter(id_departement=1).order_by('nom')
    nom_departement = "Ain"

    paginator = Paginator(villes_du_departement, 30)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # maintenant que nous avons les données, nous allons les associer
    # au context. Ainsi le Template pourra les utiliser pour générer l'affichage
    # avec les données.
    context = {
        'villes_du_departement': villes_du_departement,
        'nom_departement': nom_departement,
        'page_obj': page_obj,
    }

    # nous pouvons utiliser un objet template pour générer l'affichage puis
    # le retourner via un objet HttpResponse mais... django propose
    # une methode 'render' qui le fait pour nous, alors utilisons la :-)
    return render(request, 'previsions/departements.html', context)



def select_departement(request):

    liste_departements = Departement.objects.all()

    context = {
        'liste_departements': liste_departements,
    }

    return render(request, 'previsions/select_departement.html', context)

def display_villes(request):

    id_departement = request.POST['id_departement']

    departement = Departement.objects.get(pk=id_departement)
    villes_du_departement = Ville.objects.filter(id_departement=id_departement).order_by('nom')
    paginator = Paginator(villes_du_departement, 30)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)


    context = {
        'villes_du_departement': villes_du_departement,
        'departement': departement,
        'page_obj': page_obj,

    }
    return render(request, 'previsions/display_villes.html', context)

def add_ville(request):
    save_error = False
    is_create = True

    if request.method == 'POST':
        is_create = False

        form = VilleForm(request.POST)
        if form.is_valid():
            nom = form.cleaned_data['nom']
            code_postal = form.cleaned_data['code_postal']
            departement = form.cleaned_data['departement']

            try:
                print("enregistrement de la ville en 800")
                ville = Ville()
                ville.nom = nom
                ville.code_postal = code_postal
                ville.id_departement = departement
                ville.save()
                print('enregistrement ok')

                form = VilleForm()

            except:
                save_error = True

    else:
        form = VilleForm()

    return render(request, 'previsions/add_ville.html', {'form': form, 'save_error': save_error, 'is_create': is_create})

def favoris(request):
    liste_villes_favorites = request.session['favoris']
    context = {
        'favoris': liste_villes_favorites,
    }

    return render(request, 'previsions/favoris.html', context)


def display_previsions_ville(request):
    # on récupère la ville provenant du formulaire
    nom_ville = request.POST['ville']

    # on récupère les prévisions associées à la ville depuis la couche business
    meteo_ville_previsions = MeteoVillePrevisions(nom_ville)

    previsions_jour = meteo_ville_previsions.get_previsions_jour()
    previsions_force_vent = meteo_ville_previsions.get_previsions_force_vent()
    previsions_description = meteo_ville_previsions.get_previsions_description()

    # on construit une liste contenant des dictionnaires afin de pouvoir utiliser
    # les données dans le template
    #
    # /!\ la manipulation des éléments Python dans le template n'est pas du pure Python,
    #     c'est une syntaxe propre au langage de template de Django
    #
    #     ainsi, pour consulter dans la template une information de dictionnaire,
    #     on utilisera le "." pour définir la clé.
    #
    #     ce qui donne dans le code python
    #     ma_variable[ma_cle] = "valeur"
    #
    #     et dans le template, accédera à la valeur ainsi :
    #     {{ ma_variable.ma_cle }}

    previsions_affichage = []
    for jour in range(7):
        prevision_jour = {}
        prevision_jour["temperature"] = previsions_jour[jour]
        prevision_jour["force_vent"] = previsions_force_vent[jour]
        prevision_jour["description"] = previsions_description[jour]
        prevision_jour["jour"] = UIHelper.day_of_the_week_from_period(jour)
        prevision_jour["icon"] = "previsions/images/" + UIHelper.image_from_weather_status(previsions_description[jour])

        previsions_affichage.append(prevision_jour)

    context = {
        'ville': nom_ville,
        'previsions_affichage': previsions_affichage,
    }

    return render(request, 'previsions/display_previsions_ville.html', context)

meteosite/previsions/templates/previsions/add_ville.html
{% extends 'previsions/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form action="{% url 'previsions:add_ville'%}" method="post">
    {% csrf_token %}
    <div class="container">
        <div class="mt-6 mx-6">
        {% crispy form %}
            <button class="button is-primary" type="submit" value="Ajouter">Ajouter</button>
        </div>
    </div>
</form>
</p>

{% if save_error %}
    <p>Une erreur s'est produite lors de l'enregistrement de la ville en base de données</p>
{% else %}
    {% if is_create == False %}
    <p>La ville a bien été enregistrée en base de données</p>
    {% endif %}
{% endif %}

{% endblock content %}

meteosite/previsions/templates/previsions/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>previsions</title>
    <!-- IMPORT fa & css & bulma & js & swiper -->
    <script defer src="https://use.fontawesome.com/releases/v6.1.1/js/all.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'previsions/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'previsions/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'previsions/css/owl.theme.default.min.css' %}">
    <script src="{% static 'previsions/js/main.js' %}"></script>

</head>
<body>
<div class="hero is-fullheight background-hero">
    <div class="hero-head">
        <nav class="navbar has-background-dark" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="http://localhost:8000/">
                    <span class="is-uppercase has-text-weight-bold has-text-white">application météo</span>
                </a>
            </div>




            <div id="navbarMenu" class="navbar-menu is-active has-background-dark">
                <div class="navbar-end">
                    <div class="navbar-item">
                <a href="/previsions/logout" class="button is-light mx-1">
                    {% if user.is_authenticated %}
                    Se déconnecter de ({{user.first_name}})
                    {% else %}
                    Se connecter
                    {% endif %}
                </a>
            </div>

                    <div class="navbar-item">
                        <form action="{% url 'previsions:display_previsions_ville'%}" method="post">
                            {% csrf_token %}
                            <div class="block mr-6">
                                <div class="columns is-mobile is-gapless ">
                                    <div class="column is-full ">
                                        <div class="control">
                                            <input name="ville" class="input" type="text" placeholder="Ville...">
                                        </div>
                                    </div>
                                    <div class="column">
                                        <div class="control">
                                            <button class="button mx-1">
                                            <span class="icon">
                                              <i class="fas fa-search"></i>
                                            </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </nav>
    </div>

{% block content %}
{% endblock content %}


</div>





<script src="{% static 'previsions/js/jquery.min.js' %}"></script>
<script src="{% static 'previsions/js/owl.carousel.min.js' %}"></script>

<script>






    $('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,

    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})


</script>



</body>
</html>













<!--




{% if user.groups.all.0.name == 'favoris' %}
                <a class="navbar-item" href="/previsions/favoris" >Favoris</a>
                {% endif %} -->

meteosite/previsions/templates/previsions/departements.html
<h1>Voici la liste des villes pour le département {{nom_departement}}</h1>
<ul>
    {%for ville in page_obj %}
    <li>Ville: {{ville.nom}}, Code Postal: {{ville.code_postal}}</li>
    {% endfor %}
</ul>


        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Première</a>
            <a href="?page={{ page_obj.previous_page_number }}">Précédent</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Suivant</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Dernière &raquo;</a>
        {% endif %}

meteosite/previsions/templates/previsions/display_previsions_ville.html
{% extends 'previsions/base.html' %}
{% load static %}





{% block content %}

<div class="previsionsTitle">
    <p>Previsions pour la ville de {{ville}}</p>
</div>


<div class="previsionsCard">

    <div class="owl-carousel owl-theme">
        {% for prevision in previsions_affichage %}


            <div class="card">

                <div class="cardHeader">
                  <span>{{prevision.jour}}</span>
                </div>

                <div class="cardBody">
                    <img src="{% static prevision.icon %}">
                    <span>{{prevision.temperature|floatformat:0}}°</span>
                </div>

                <div class="cardFooter">

                  <div class="cardDescription">
                    <span>{{prevision.description}}</span>
                  </div>

                  <div class="wind">
                    <i class="fa-solid fa-wind"></i>
                    <span>{{prevision.force_vent|floatformat:0}} Km/h</span>
                  </div>

                </div>
            </div>
        {% endfor %}

    </div>


</div>

{% endblock content %}

meteosite/previsions/templates/previsions/display_villes.html
<h1>Voici la liste des villes pour le département {{departement.nom}}</h1>

<ul>
    {% for ville in page_obj %}

    <li>{{ville.nom}}, {{ville.code_postal}}</li>
    {% endfor %}
</ul>

        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">Précédent</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Suivant</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Dernière &raquo;</a>
        {% endif %}

meteosite/previsions/templates/previsions/favoris.html
{% extends 'previsions/base.html' %}
{% block content %}

<div class="container">
    <article class="panel my-5 mx-5">
        <p class="panel-heading">Favoris</p>
        {% for ville in favoris %}
        <a class="panel-block">
            <span class="panel-icon">
                <i class="fas fa-city" aria-hidden="true"></i>
            </span>
            {{ ville}}
        </a>
        {% endfor %}
    </article>
</div>

{% endblock content %}

meteosite/previsions/templates/previsions/index.html
{% extends 'previsions/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}


<div class="indexTitle">
    <h1>Application Météo</h1>
    <h2>Utilisation du Framework Django</h2>
</div>



{% endblock content %}

meteosite/previsions/templates/previsions/select_departement.html
{% extends 'previsions/base.html' %}
{% block content %}

<h1>Formulaire pour consulter les villes d'un departement</h1>
<form action="{% url 'previsions:display_villes'%}" method="post">
    {% csrf_token %}
    <select name="id_departement">
        {% for departement in liste_departements %}
        <option value="{{departement.id_departement}}" name="id_departement">{{departement.nom}}</option>
        {% endfor %}
    </select>
    <input type="submit">
</form>

{% endblock content %}